#!/bin/sh
string1="abc"
string2="abd"
if [ $string1 = $string2 ]; then
    echo "string1 equal to string2"
else
    echo "string1 not equal to string2"
fi

if [ $string2 != $string1 ]; then
    echo "string2 not equal to string1"
else
    echo "string2 equal to string1" 
fi

if [ $string1 ]; then
    echo "string1 is not empty"
else
    echo "string1 is empty"
fi

if [ -n $string2 ]; then
    echo "string2 has a length greater than zero"
else
    echo "string2 has length equal to zero"
fi

if [ -z $string1 ]; then
    echo "string1 has a length equal to zero"
else
    echo "string1 has a length greater than zero"
fi

# bash compare1
# string1 not equal to string2
# string2 not equal to string1
# string1 is not empty
# string2 has a length greater than zero
# string1 has a length greater than zero