#!/bin/sh
# Name display program
if [ $# -eq 0 ]
then
    echo "Name not provided"
else
    echo "Your name is "$1
fi

# Output

# bash mypgml
# Name not provided

# bash mypgml Sandra
# Your name is Sandra